#import = [
##  "~/.config/alacritty/themes/themes/coolnight.toml"
#]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 2
dimensions = { columns=130, lines=30 }

opacity = 0.93
blur = true

option_as_alt = "Both"
decorations = "Buttonless"
#decorations = "None"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.dim]
black   = "#3c3836"
red     = "#9d0006"
green   = "#79740e"
yellow  = "#b57614"
blue    = "#076678"
magenta = "#8f3f71"
cyan    = "#427b58"
white   = "#928374"
